version: '3.9'
services:
  db:
    image: postgres:15.2-alpine
    container_name: auth-db
    hostname: auth-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: postgres -p ${POSTGRES_PORT}
volumes:
  db-data:
